### ISSUE TITLE
[BUG] A stopped host publishes two host_stopped events

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#469]
**Describe the bug**

When you stop a wasmCloud host, it publishes two `host_stopped` events in the process of shutting down. With the [lattice-observer](https://github.com/wasmCloud/lattice-observer), this can end up double-handling the same event which is unnecessary

**To Reproduce**

1. Start a wasmcloud host
2. Use the NATS CLI to subscribe to `wasmbus.evt.*`
3. Stop it with `./bin/wasmcloud_host stop`
4. Observe two host_stopped events

**Expected behavior**

I'd expect a single `host_stopped` event to be published

**Comment by giusdp** [comment]
I tried to reproduce this bug but I've seen only one event. Maybe it was fixed with the recent supervisor tree refactor.

**Comment by brooksmtownsend** [comment]
I still get two, unfortunately. I tested by running `iex -S mix` and then using `wash ctl stop` to stop the host.
```
[#8] Received on "wasmbus.evt.default"
{"data":{"labels":{"hostcore.arch":"aarch64","hostcore.os":"macos","hostcore.osfamily":"unix"}},"datacontenttype":"application/json","id":"7a4948d3-0ba4-4970-bbfb-c1b5cff634d2","source":"NCM5CT4WJUB3GTRJ2AFYXDIHK7YRMX2TIBJXOCZE2AU5OYNKDPBYONLV","specversion":"1.0","time":"2022-12-12T21:13:04.810973Z","type":"com.wasmcloud.lattice.host_stopped"}

[#9] Received on "wasmbus.evt.default"
{"data":{"labels":{"hostcore.arch":"aarch64","hostcore.os":"macos","hostcore.osfamily":"unix"}},"datacontenttype":"application/json","id":"90c0eb48-cc59-4d15-8ee3-737c52629169","source":"NCM5CT4WJUB3GTRJ2AFYXDIHK7YRMX2TIBJXOCZE2AU5OYNKDPBYONLV","specversion":"1.0","time":"2022-12-12T21:13:05.111611Z","type":"com.wasmcloud.lattice.host_stopped"}
```
